### ISSUE TITLE
Manual Oculus game path addition

### ISSUE THREAD

**Issue by Jock90** [Jeshibu/Playnite-OculusLibrary#2]
Like a number of people, I am playing their Oculus games on another VR headset (e.g. I now use an HP Reverb G2) through the Revive plugin. I don't have my old Oculus Rift (like many folks), but do have the games I purchased installed on a separate hard drive. Your plugin scans the Windows registry to pick up any Oculus paths. Unfortunately, this fails here since there's no registry entry.
 
To overcome this, is is possible to add a feature that allows the paths to one/more Oculus game libraries to be added manually, then your plugin could pick them up?

**Comment by Jeshibu** [comment]
The 2.5 update can fetch Rift games from your meta/oculus account online. You can then edit the install location and status, and add a play action to them.
