### ISSUE TITLE
Library scrape failure?

### ISSUE THREAD

**Issue by quidnun** [Jeshibu/Playnite-OculusLibrary#3]
When I update Oculus library it makes a single game entry with multiple Oculus sources and the title of each is "Update your Browser | Facebook". There are correct game icons and I can launch but it doesn't grab the whole library, I guess because they are all shoved into the single entry?

**Comment by Jeshibu** [comment]
Can you check if this still happens with the latest release?

**Comment by quidnun** [comment]
most are still returning the "Update your Browser" but if I remove them and update the library again I can do it multiple times until it finds all of them and puts them into separate entries. Then just manually do the metadata which is missing. So that's the workaround I guess. Thanks
