### ISSUE TITLE
Playnite No Longer Finds Oculus Client

### ISSUE THREAD

**Issue by GCTuba** [Jeshibu/Playnite-OculusLibrary#4]
For a few days now, every time I start up Playnite, it says "Failed to import games from Oculus. One or more errors occurred." Of course it doesn't tell me what the errors are. I reinstalled the Oculus client and removed and readded the library integration and it still has an error. The games I imported from Oculus on initial setup a few months ago are still there.

**Comment by Jeshibu** [comment]
Are you in the USA?
Could you check if this still occurs with the latest release?

**Comment by GCTuba** [comment]
Yes, I'm in USA. I updated the Oculus game library and it didn't throw out in errors. However, when I try to open the Oculus client from within Playnite, I still get an error that says "Startup Error. Failed to start the application. The system cannot find the file specified."

**Comment by Jeshibu** [comment]
That's a different thing altogether, but have you moved the Oculus app manually? It launches OculusClient.exe in the program's uninstall folder (as fetched from the registry). Maybe try repairing/reinstalling the Oculus app.

**Comment by GCTuba** [comment]
I repaired the installation and still got the same error. I never moved it manually.

**Comment by Jeshibu** [comment]
Should be fixed now with 2.5.1
