### ISSUE TITLE
'Name' = '<null>' in cookie not valid

### ISSUE THREAD

**Issue by norrin77** [Jeshibu/Playnite-OculusLibrary#5]
Hi Jeshibu, thanks for you great plugin.

I have a problem after reinstalling/trying to update the list of games, using options "Import Oculus Rift (PCVR) games from your Oculus account" and "Import Quest games from your Oculus account".

I get this error message:

![imagen](https://github.com/Jeshibu/Playnite-OculusLibrary/assets/5031859/be53e1a1-19de-4f89-bbdf-75a4d30cef18)

If I just leave alone the import of currently installed PCVR games, it works, but no metadata is retrieved (and no Quest games from the account, of course).

Thanks in advance.

**Comment by norrin77** [comment]
Ok I figured out myself: in GraphQLClient.cs, at line 98

https://github.com/Jeshibu/Playnite-OculusLibrary/blob/4c8e7c0d419fbd4c6722928c46c2cb8d3e950ab5/OculusLibrary/DataExtraction/GraphQLClient.cs#L98

it seems that GetBrowserResponse is generating wrong cookies if Value = null. So I just added:

`.Where(c => c.Value != null)`

before the select.

Best regards,

**Comment by RichardGG** [comment]
@norrin77 @Jeshibu Any chance someone could apply this fix and make a release?
I've had this issue for a long time.

**Comment by Jeshibu** [comment]
Forgot to release this, my bad. It's out now.
