### ISSUE TITLE
Error on launch locating library

### ISSUE THREAD

**Issue by jeremymeyers** [Jeshibu/Playnite-OculusLibrary#6]
got the following error when scanning.

<img width="176" alt="Screenshot 2023-12-23 105330" src="https://github.com/Jeshibu/Playnite-OculusLibrary/assets/3514095/4fa6bebc-edec-4bf4-9a50-21934b85171b">

**Comment by Jeshibu** [comment]
Try reinstalling your Oculus client. If that doesn't work, where is that folder located?

**Comment by Jeshibu** [comment]
Closing due to no response.
