### ISSUE TITLE
Oculus App Lab titles don't seem to fetch metadata

### ISSUE THREAD

**Issue by atkulp** [Jeshibu/Playnite-OculusLibrary#7]
I have a number of app lab titles in my library, and they don't include any metadata. I've tried to manually refresh from multiple sources and still nothing.

Examples:
- https://www.meta.com/experiences/6514531415240007
- https://www.meta.com/experiences/3158342884265828
- https://www.meta.com/experiences/5182109171819582

**Comment by Jeshibu** [comment]
Retreat still gives me description, install size, links, features, etc. Are you not getting any of these? What's your locale?

**Comment by Jeshibu** [comment]
Just tried again with Nightmare Tag, and having no issues. Reopen if this is still happening.
